version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable # the primary container, where your job's commands are run
        auth:
          username: prepavenir
          password: 2xHNsPcdhQnpV3S  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command